  
unittest:
    platforms:
        - mega2560
    libraries:
      - "Adafruit BusIO"
      - "Adafruit MAX31865"
      - "Ethernet"
      - "LiquidCrystal"
      - "RTClib"
      - "Keypad"

compile:
    platforms:
      - mega2560
    libraries:
      - "Adafruit BusIO"
      - "Adafruit MAX31865"
      - "Ethernet"
      - "LiquidCrystal"
      - "RTClib"
      - "Keypad"
