platforms:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega2560__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_MEGA2560
      warnings:
        - no-unknown-attributes
        - no-address-of-packed-member
      flags:

unittest:
  platforms:
    - mega2560
  libraries:
    - "Adafruit BusIO"
    - "Adafruit MAX31865 library"
    - "PID_v2"
    - "Ethernet"
    - "LiquidCrystal"
    - "RTClib"
    - "Keypad"
    - "SdFat"

compile:
  platforms:
    - mega2560
  libraries:
    - "Adafruit BusIO"
    - "Adafruit MAX31865 library"
    - "PID_v2"
    - "Ethernet"
    - "LiquidCrystal"
    - "RTClib"
    - "Keypad"
    - "SdFat"
